on:
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    if: |
      github.event.sender.type != 'Bot' &&
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/') &&
      (
        github.event.comment.author_association == 'MEMBER' || 
        github.event.comment.author_association == 'COLLABORATOR' || 
        github.event.comment.author_association == 'OWNER'
      )

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: PR Agent

    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          CONFIG.MODEL: "deepseek/deepseek-chat"
          CONFIG.FALLBACK_MODELS: "['deepseek/deepseek-chat']"
          DEEPSEEK.KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
